---
name: NORA3_ERA5
channels:
- conda-forge

dependencies:
- python=3.8
- netcdf4
- numpy
- cartopy
- xarray
- toolz
- dask # in case of missing deps; please try replacing with dask[array] or dask[complete]

# Install conda environment (one-time operation):
# $ conda env create -f conda_environment.yml
# Activate environment
# $ conda activate NORA3_ERA5
